### PR TITLE
rockpi-4b-rk3399: Initial support for this board

### PR DESCRIPTION
**Pull request by floion**
Changelog-entry: Add initial support for rockpi-4b-rk3399
Signed-off-by: Florin Sarbu <florin@balena.io>

### CODE REVIEW

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by stathismor** [comment]
@balena-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@balena-ci retest

**Comment by floion** [comment]
@balena-ci retest

**Comment by floion** [comment]
@balena-ci I self-certify!

**Pull request merged**
